### ISSUE TITLE
methodology leads to incorrect recommendations

### ISSUE THREAD

**Issue by alexzaworski** [alexzaworski/unit-golfer#2]
Example:

```
node unit-golf.js 265

Best: 37ex, offset by: 0.36 pixels

Rest:
...
7.01cm (offset: -0.15)
```

```
node unit-golf.js 265 1

Best: 7cm, offset by: -0.53 pixels
```
It's probably because of internal rounding stuff, but the actual width of a `7cm` element in Chrome is `264.5625`, which at `0.44` should fall within the default `0.5` offset

I don't know of a good way we can handle this without having a rendering engine, we probably need to look at a puppeteer solution for totally accurate values.

**Comment by CyberAP** [comment]
Strangely enough Chrome is giving me different values from what we have in the script.
For example `1cm` equals to `37.7890625px` on my machine. But in the script it's `37.78125px`. What value do you have in your Chrome? Could it be enviroment dependent?

**Comment by CyberAP** [comment]
Though I can't deny the fact that `cm` doesn't work as a linear value in Chrome.

`7cm` gives me `264.5625px`, while it should be `264.5234375px`.

**Comment by alexzaworski** [comment]
`mm` behaves the same way, and I assume others too but I haven't tested

I definitely get `37.78125` for `1cm`

```
const d = document.createElement('div');
document.body.appendChild(d);
d.setAttribute('style', 'width:1cm');
console.log(d.getBoundingClientRect().width)

// 37.78125
```

**Comment by CyberAP** [comment]
Found the code reliable for approximations. Maybe we can dig something out of it: 

https://chromium.googlesource.com/chromium/src/+/master/third_party/blink/renderer/core/css/css_primitive_value.cc

https://chromium.googlesource.com/chromium/src/+/master/third_party/blink/renderer/core/css/css_primitive_value.h

On the first glance it seems to be dependent on the resolution. That means we have to know what resolution does CSSBattle's machine has.

**Comment by alexzaworski** [comment]
That's part of the reason I was investigating puppeteer (which I would bet they use, or something very similar)

That should normalize stuff right?

```
const browser = await puppeteer.launch();
const page = await browser.newPage();
const width = await page.evaluate(() => {
  const d = document.createElement('div');
  document.body.appendChild(d);
  d.setAttribute('style', 'width:1cm');
  return (d.getBoundingClientRect().width)
});
console.log(width);
await browser.close();
```

This yields the same value I was getting on https://try-puppeteer.appspot.com/

**Comment by alexzaworski** [comment]
Though maybe we use this to guess at a resolution and then also try to reverse engineer the rounding, idk

**Comment by CyberAP** [comment]
Puppeteer is the easiest way to do this, yes. I still want to know how they do it internally after all. Maybe that'll give an answer on why this value is not linear and differs from enviroment to enviroment.

**Comment by alexzaworski** [comment]
Yeah sounds good. I should have time after work today to whip up a version using puppeteer, in the meantime if you find anything nifty in chromium source code let me know
