### ISSUE TITLE
support conversion from all units

### ISSUE THREAD

**Issue by alexzaworski** [alexzaworski/unit-golfer#3]
Sucks to look at something like '9q' and have to convert back to pixels to check for optimizations

**Comment by CyberAP** [comment]
I found myself thinking the same, but wouldn't `9q` still give you `9q`? This would be actually trivial to do.

**Comment by alexzaworski** [comment]
9q was a really terrible example, my bad. If you had something like 23vw and you're trying to optimize it kinda sucks to have to go 23vw -> 92px -> 1in
